### ISSUE TITLE
Error in RadauM

### ISSUE THREAD

**Issue by vick2075** [tjczec01/RadauD#2]
In ODE function of the sort: "def f(t, u)", when the ODE equation uses t, there is an error of sort:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\ODEs\scipyradau\testradsci.py", line 125, in <module>
    sol.step()
  File "C:\Users\dell\Desktop\ODEs\scipyradau\base.py", line 181, in step
    success, message = self._step_impl()
  File "C:\Users\dell\Desktop\ODEs\scipyradau\RadauM.py", line 702, in _step_impl
    converged, n_iter, Z, rate = solve_collocation_system(
  File "C:\Users\dell\Desktop\ODEs\scipyradau\RadauM.py", line 320, in solve_collocation_system
    F[i] = fun(mv(t, prec) + ch[i], y + Z[i])
  File "C:\Users\dell\Desktop\ODEs\scipyradau\base.py", line 138, in fun
    return self.fun_single(t, y)
  File "C:\Users\dell\Desktop\ODEs\scipyradau\base.py", line 20, in fun_wrapped
    return np.asarray(fun(t, y), dtype=dtype)
  File "C:\Users\dell\Desktop\ODEs\scipyradau\testradsci.py", line 11, in f
    deriv = [ (4.0 * np.exp(0.8 * t)) - (0.5 * u[0]) ]
TypeError: loop of ufunc does not support argument 0 of type mpf which has no callable exp method

The "deriv" contains the ODE equation. In this instance it is a single ODE but that uses t as well. I have used RadauM for coupled ODE when t is unused successfully.

**Comment by tjczec01** [comment]
This doesn't surprise me at all. I built this when I was working on my master thesis in order to perhaps achieve better results for the ODE system that I was using at the time. For this package I simply applied the numerically unbounded result I built with other packages and applied it to the ODE system I was currently using which didn't have a derivative with respect to the 't" variable. I simply followed the open-source "solve_ivp" code and applied the Decimal based matrix functions I built to replicate the same results as the normal "solve_ivp" method. This code was mostly uploaded in an effort to conserve my efforts at the time and perhaps aid the effort of others who would want to use my code to build a more robust, professional code base using what I had made so far.

**Comment by vick2075** [comment]
So any suggestion?

**Comment by tjczec01** [comment]
I would need to see your code in its entirety, as I am not sure what u[0] is and if I remember correctly you can't use numpy arrays with [mpmath](https://mpmath.org/doc/current/) or [Decimal](https://docs.python.org/3/library/decimal.html) as it throws an error. however if I was to guess I don't think that equation would need an accuracy past what normal float numbers will get you.

**Comment by vick2075** [comment]
In def f(t, y):
return  [ (4.0 * np.exp(0.8 * t)) - (0.5 * y) ]

u[0] is simply the only variable y.

The ODE in question is used to gauge the solver's order and accuracy, without the use of variable step size and other features that enhance the solver.

For example on this particular problem, RK4 is about 10e-04 accurate whereas Radau5 is about 10e-06. So I was wondering what accuracy would Radau5 with precise digits when used with mpmath get?

**Comment by tjczec01** [comment]
I unfortunately wouldn't know much about the respective accuracy as I created this to get past overflow errors for the large and complex system of coupled ODEs I had to solve for my masters thesis. IIRC the answer obtained from using this for most normal ODEs systems almost identically matched the answers from the base solver until around 10-15 decimal places past 0. You may find a more technical and concrete answer by directly asking the creates of the Radau method in python at Scipy.

**Comment by vick2075** [comment]
ok thanks anyway!
